#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ImageEffects.Resource", IsApplication=true)]

namespace ImageEffects
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Lenna = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int autofix = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int brightness = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int bw = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int contrast = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int crossprocess = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int documentary = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int duotone = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int effectsview = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int filllight = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int fisheye = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int fliphor = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int flipvert = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int grain = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int grayscale = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int lomoish = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int negative = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int none = 2131099649;
			
			// aapt resource value: 0x7f060011
			public const int posterize = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int rotate = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int saturate = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int sepia = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int sharpen = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int temperature = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int tint = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int vignette = 2131099672;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int options_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int autofix = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int brightness = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int bw = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int contrast = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int crossprocess = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int documentary = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int duotone = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int filllight = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int fisheye = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int fliphor = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int flipvert = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int grain = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int grayscale = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int lomoish = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int negative = 2130968594;
			
			// aapt resource value: 0x7f040003
			public const int none = 2130968579;
			
			// aapt resource value: 0x7f040013
			public const int posterize = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int rotate = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int saturate = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int sepia = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int sharpen = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int temperature = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int tint = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int vignette = 2130968602;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
